### PR TITLE
[INTERNAL] Move Cachebuster config documentation to correct section

### PR DESCRIPTION
**Pull request by Thodd**
Feature was implemented with https://github.com/SAP/ui5-builder/pull/241.

### CODE REVIEW

**Comment by Thodd** [comment]
Hm... I just noticed by IDE removed some trailing whitespaces.
Are they left intentionally...?

**Comment by matz3** [comment]
@Thodd yes, 2 spaces will create a line break in markdown files. You might need to install the [EditorConfig](https://editorconfig.org/) in your IDE in order to use the [settings of this project (to not remove them)](https://github.com/SAP/ui5-project/blob/master/.editorconfig#L20).

**Comment by Thodd** [comment]
Ok didn't know that. Fixed.

**Comment by RandomByte** [comment]
This documentation also exists here now: https://github.com/SAP/ui5-tooling/edit/master/docs/pages/Configuration.md

It would be nice to make the same change there. Optionally we could replace this markdown with a reference to the new documentation at https://sap.github.io/ui5-tooling/pages/Configuration/

**Comment by Thodd** [comment]
https://github.com/SAP/ui5-tooling/pull/170

**Pull request merged**
